- docs/source/PCs/ARM/iMX6UL/Manuals/Hardware/Resources/connectivity
- docs/source/PCs/ARM/iMX6UL/Manuals/Hardware/Resources/table
> Updated CS10600U070

- docs/source/PCs/ARM/iMX6Q/Manuals/Software/Android_43.rst
- docs/source/PCs/ARM/iMX6Q/Manuals/Software/Linux_Qt55.rst
- docs/source/PCs/ARM/iMX6Q/Manuals/Software/Ubuntu_12.rst
- docs/source/PCs/ARM/iMX6Q/Manuals/Software/Ubuntu_14.rst
Add Links for some tools for IMX6Q products
> Add Links for some tools

- docs/source/PCs/ARM/iMX6Q/Manuals/Software/Android_60.rst
Add tools link for Android6.0 software documentation.
> Add some tools link

- docs/source/PCs/Pi/A72/Manuals/Hardware/CS10768RA4150.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS19108RA4133.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS19108RA4156.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/Resources/Camera_cs12800ra4101
- docs/source/PCs/Pi/A72/Manuals/Hardware/Resources/LAN_cs19108ra4133
- docs/source/PCs/Pi/A72/Manuals/Hardware/Resources/power_cs19108ra4133
fix follow,
LAN and Power pictures lost.
table use wrong ref.
> Some picture lost

- docs/source/PCs/Pi/A53/Manuals/Hardware/CS10600RA070.rst
- docs/source/PCs/Pi/A53/Manuals/Hardware/CS12800RA101.rst
- docs/source/PCs/Pi/A53/Manuals/Hardware/index.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS10600RA4070.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS10768RA4150.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS12800RA4101.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS19108RA4133.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS19108RA4156.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/index.rst
Rename Industrial Pi products names.
> Update Industrial Pi products name

- docs/source/PCs/ARM/iMX6UL/OS_Downloads/CS10600U070.rst
- docs/source/PCs/Pi/Software/Resources/Download_IMG
1. Update Software Manual for Industrial Pi products.
2. Release new system for CS10600U070.
> Some update

- docs/source/Monitors/PIM-190-C.rst
- docs/source/Monitors/index.rst
Modify resolution of Monitors like index.rst file and PIM-190-C.rst file.
> Modify resolution of Monitors

- docs/source/PCs/ARM/RK3399/OS_Downloads/CS12800R101.rst
- docs/source/PCs/ARM/RK3399/OS_Downloads/index.rst
Add OS Download for CS12800R101
> Add OS Download

- docs/source/PCs/ARM/RK3568/Manuals/Hardware/CS12800-RK3568-070P.rst
- docs/source/PCs/ARM/RK3568/Manuals/Hardware/CS12800-RK3568-101P.rst
- docs/source/PCs/ARM/RK3568/Manuals/Hardware/index.rst
Remove -C letter for RK3568 platform.
> Remove -C letter

- docs/source/PCs/ARM/RK3399/Manuals/Hardware/CS19108R133P.rst
- docs/source/PCs/ARM/RK3399/Manuals/Hardware/index.rst
Update PPC-A72-133-P product name.
> Update Product Name

- docs/source/PCs/Pi/Software/AIO156AndroidSystem.rst
- docs/source/PCs/Pi/Software/AIO156StartGuide.rst
- docs/source/PCs/Pi/Software/index.rst
Add Android13 Guide for AIO-CM4-156 product.
> Add Android13 Guide

- docs/source/PCs/Pi/A72/Manuals/Hardware/index.rst
Fix image error for PPC-CM4-050 product.
> Fix image error

- docs/source/PCs/ARM/RK3568/OS_Downloads/CS10600-RK3568-070P.rst
- docs/source/PCs/ARM/RK3568/OS_Downloads/CS12720-RK3568-050P.rst
- docs/source/PCs/ARM/RK3568/OS_Downloads/index.rst
Add OS download link for RK3568 5 and 7 products.
> Add OS download link

- docs/source/PCs/ARM/iMX6Q/Manuals/Hardware/CS10768F121.rst
- docs/source/PCs/ARM/iMX6Q/Manuals/Hardware/CS10768F150.rst
- docs/source/PCs/ARM/iMX6Q/Manuals/Hardware/CS12102F170.rst
- docs/source/PCs/ARM/iMX6Q/Manuals/Hardware/CS19108F215.rst
- docs/source/PCs/Pi/Software/Debian.rst
- docs/source/PCs/Pi/Software/index.rst
1. Update software manual for Industrial-Pi products.
2. Update hardware features for A9 121, 150,170,215.
> Some manuals update

- docs/source/PCs/ARM/RK3399/Manuals/Hardware/CS19108R236P.rst
- docs/source/PCs/ARM/RK3399/Manuals/Hardware/index.rst
Remove -P
[Preview](http://cd2.jljgxx.com/PCs/ARM/RK3399/Manuals/Hardware/CS19108R236P.html)
> Update RK3399 236 product naming.

- docs/source/PCs/Pi/A72/Manuals/Hardware/CS12720RA4050-C121.rst
5 inch CM4 product needs a customised case.
> Minor changes on CM4 Camera doc.

- docs/source/PCs/Pi/A72/Manuals/Hardware/CS10600RA4070.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS10600RA4070P-D.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS12720RA4050-C121.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/Resources/CS12800RA4101/base_replaces_cs12800ra4101
- docs/source/PCs/Pi/A72/Manuals/Hardware/Resources/USB
[Preview](http://cd2.jljgxx.com/PCs/Pi/A72/Manuals/Hardware/CS12720RA4050-C121.html)
> Fix CM4 USB.

- docs/source/PCs/ARM/RK3399/Manuals/Hardware/CS19108R236P.rst
- docs/source/PCs/ARM/RK3568/Manuals/Hardware/CS19108-RK3568-236P.rst
- docs/source/PCs/ARM/RK3568/Manuals/Software/Android_11.rst
- docs/source/PCs/Intel/J6412/Manuals/Hardware/PPC-J6412-236-C.rst
- docs/source/PCs/Pi/A72/Manuals/Hardware/CS19108RA4236.rst
[Preview](http://cd.jljgxx.com/PCs/ARM/RK3399/Manuals/Hardware/CS19108R236P.html)
> Update 23.6 products power consumption and dimension.

- docs/source/PCs/ARM/RK3568/OS_Downloads/CS19108-RK3568-133P.rst
- docs/source/PCs/ARM/RK3568/OS_Downloads/CS19108-RK3568-156P.rst
- docs/source/PCs/ARM/iMX8MP/Manuals/Hardware/CS10600-IMX8MP-070P.rst
- docs/source/PCs/ARM/iMX8MP/Manuals/Hardware/Resources/CS10600-IMX8MP-070P/gpio
- docs/source/PCs/ARM/iMX8MP/Manuals/Hardware/index.rst
- docs/source/PCs/ARM/iMX8MP/Manuals/Software/Android_12.rst
- docs/source/PCs/ARM/iMX8MP/Manuals/Software/index.rst
[Preview](http://cd3.jljgxx.com/PCs/ARM/iMX8MP/Manuals/Hardware/index.html)
> Update 8MP name

- docs/source/PCs/Pi/Software/AIO156StartGuide.rst
- docs/source/PCs/Pi/Software/Debian.rst
- docs/source/PCs/Pi/Software/index.rst
Rename Debian to Raspberry Pi OS.
[Preview](http://cd3.jljgxx.com/PCs/Pi/Software/index.html)
> Update Pi OS naming.

- docs/source/PCs/ARM/AM335X/Manuals/Hardware/CS10768T097.rst
- docs/source/PCs/ARM/AM335X/Manuals/Hardware/CS80480T050.rst
- docs/source/PCs/ARM/AM335X/Manuals/Hardware/CS80480T070-R233.rst
- docs/source/PCs/ARM/AM335X/Manuals/Hardware/Resources/connectivity
- docs/source/PCs/ARM/AM335X/Manuals/Hardware/index.rst
[Preview](http://cd2.jljgxx.com/PCs/ARM/AM335X/Manuals/Hardware/index.html)
> Add AM3354 070 R

- docs/source/_templates/layout.html
- docs/source/index.html
Test plausible and matomo analytics.
> Add matomo and plausible.

- docs/source/PCs/ARM/RK3399/Manuals/Hardware/Legacy_Resources/101/ordering
- docs/source/PCs/ARM/RK3399/Manuals/Hardware/Legacy_Resources/133_150_156_215/ordering
- docs/source/PCs/ARM/RK3399/Manuals/Hardware/Resources/ordering
Changed Chipsee Linux to Buildroot Linux QT5.14.
> Update RK3399 OS naming.

- docs/source/PCs/Pi/A72/Manuals/Hardware/CS10600RA4070.rst
To match the technical drawing, and be more precise.
> Update dimension of epc-cm4-070

- docs/source/PCs/ARM/iMX6Q/Manuals/Hardware/CS12800F101.rst
To answer a user's question from the website.
> Update mounting of A9-101-C

- docs/source/PCs/ARM/iMX6Q/OS_Downloads/CS14900F190.rst
Swapped to correct the position.
> Fix imx6q-190 download link
